### ISSUE TITLE
Implementing OpenMP functionality for phylosmith on macOS

### ISSUE THREAD

**Issue by JacobRPrice** [schuyler-smith/phylosmith#16]
I'd like to preface this question by stating that this is not an issue directly related to the functionality within `phylosmith`, but it may be common enough that it's worth submitting an issue here and documenting possible solutions. 

While installing `phylosmith` I experienced a warning that I have not seen before: 
```
configure: WARNING: OpenMP unavailable and turned off.
```
Here is the full stdout that I'm seeing (I'm sorry, as the printout is long). I've included my sessionInfo() at the beginning/top of the block in case it is relevant. 

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   
> devtools::install_github('schuyler-smith/phylosmith', force = TRUE)
Downloading GitHub repo schuyler-smith/phylosmith@HEAD
✓  checking for file ‘/private/var/folders/hr/_lct3llj6nq692y3tb_y6m700000gn/T/Rtmp2St528/remotes106a53ea5a15/schuyler-smith-phylosmith-04107da/DESCRIPTION’ ...
─  preparing ‘phylosmith’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘phylosmith_1.0.6.tar.gz’
   
* installing *source* package ‘phylosmith’ ...
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C++ preprocessor... clang++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether clang++ accepts -g... (cached) yes
checking whether g++ version is sufficient... checking for macOS... found
configure: WARNING: OpenMP unavailable and turned off.
configure: creating ./config.status
config.status: creating src/Makevars
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include  -I../inst/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include  -I../inst/include  -fPIC  -Wall -g -O2  -c correlations_Rcpp.cpp -o correlations_Rcpp.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o phylosmith.so RcppExports.o correlations_Rcpp.o -DARMA_64BIT_WORD -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-phylosmith/00new/phylosmith/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (phylosmith)
```

From this output it looks like I have C++ and clang and that they are OK for what `phylosmith` (or R) needs them for, but let's double check... (it may be that the components have incompatible versions): 

```
PRICE-MacBook:~ jprice$ which xcode-select
/usr/bin/xcode-select
PRICE-MacBook:~ jprice$ xcode-select --version
xcode-select version 2349.
PRICE-MacBook:~ jprice$ 
PRICE-MacBook:~ jprice$ which c++
/usr/bin/c++
PRICE-MacBook:~ jprice$ c++ --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
PRICE-MacBook:~ jprice$ 
PRICE-MacBook:~ jprice$ which clang
/usr/bin/clang
PRICE-MacBook:~ jprice$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
PRICE-MacBook:~ jprice$ 
PRICE-MacBook:~ jprice$ which gfortran
/usr/local/bin/gfortran
PRICE-MacBook:~ jprice$ gfortran --version
GNU Fortran (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PRICE-MacBook:~ jprice$ 
```

In summary, I have Xcode, C++, clang, and gfortran all installed, and (I believe) they're located in the correct place and are located on my `$PATH`. 

```
PRICE-MacBook:~ jprice$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
```

Now I've got to figure out how to get OpenMP installed and recognized by R. I haven't been able to find a clear answer on how to go about doing it. As I said at the beginning, I know this isn't a specific problem/issue with phylosmith, but hopefully you could provide some insight or resources on how to go about doing this. 

The funny thing is that on my non-work mac, I could install `phylosmith` just fine, and OpenMP was recognized, so I must have done something different when I was setting up my work machine when I started my current position. If need be, I can uninstall R and all of the individual components and start from scratch, although I would like to avoid that if at all possible as I'm currently developing two packages and have a couple of projects open on this machine. 

Any insight that you'd be able to provide would be greatly appreciated. 

Thanks!

Jake

**Comment by schuyler-smith** [comment]
Hi Jake,

Hopefully we can figure this out! `phylosmith` is still installing correctly and should work fine, it's just warning that OpenMP isn't available, which is the program used for the parallel-processing in the co-occurrence calculations (the function should still work, just limited to using a single thread). Clang, the c++ compiler shipped with Macs, historically did not support OpenMP, so the installation is designed to turn it off if it can't find it. I don't have a Mac to test these things out and find if any of them work, so I will just post what I found people have said works that make sense to me. 

My understanding is that recent versions (past 3-4 years) of clang support OpenMP, which may be why your personal Mac is able to use OpenMP and your work Mac is not. The first thing I would do is check if there is any update for clang on your work Mac. From what I am seeing, High Sierra (the OS version your work Mac is running) likely had an OpenMP compatible version of clang, but I don't know enough about Apple to know if they ship the updated compilers in the OS builds or if you need to update them yourself. It's worth a shot because I think it'd be the simplest solution if it works!

If it is up to date, then some people have noted that you need to have `llvm` and  `libomp` both installed on your machine for OpenMP to work. The easiest way to do this is with Homebrew, a package management system for Macs. If you have Homebrew installed already, you should be able to install those two packages by typing the following two commands into your terminal

```
brew install llvm
brew install libomp
```

If you don't have Homebrew, it can be installed with 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
as per their [website](https://brew.sh/).

If these two things don't work, then I think the next step would be installing a second c++ compiler, which isn't as intimidating as it sounds, but I still would want to avoid it if the first two suggestions will solve the issue!

Let me know if this works! Or if it doesn't and you want to try the second compiler option, I can help explain what to do.

Schuyler
