### ISSUE TITLE
Question regarding us of unique_taxa()

### ISSUE THREAD

**Issue by gcuster1991** [schuyler-smith/phylosmith#21]
Hi Schuyler,
Thanks for putting this package together. It is a great resource. 

I'm  in the process of analyzing 16S amplicon data generated from honey bee hives. I'm using the unique_taxa function to look for  taxa that are endemic to specific sites. As specified below, I pull out those taxa that are only found in a single site. Is there anyway to relax this a bit and return those that occur in some fraction of the total sites? Say I wanted to pull taxa that occur at less than 3 sites. Would this be possible? 

Thanks,
Gordon

```{r}
unique_genera_to_site_tax<-unique_taxa(phyloseq_obj = bb16S_bac_rarefy_tax_genus, treatment = "Site")
```

**Comment by schuyler-smith** [comment]
Hi! Thank you, I am glad that you are finding it useful!

You can definitely do this. The functions for `unique_taxa()` and `common_taxa()` are actually just exploiting `taxa_filter()`

`taxa_filter()` filters taxa outside the proportion threshold of samples with observations set by the argument `frequency`. By default, this filters taxa seen in a frequency of samples `below` that given threshold. If you set the argument `below = TRUE` though, it should return taxa seen in a proportion of samples less than that. If you want exactly 3 samples, you would need to set the `frequency` to some function of your total number of samples, but it may need some finessing so that it's not as precise if the total number of samples is not evenly divisible by 3.

Let me know if that does what you are wanting or if I misunderstood the question, or if there is anything else I might be able to help with!
